<!DOCTYPE HTML>
<html>
<head>
<title>::: note :::</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width"> <!-- width=1150, width=device-width, initial-scale=1.0 -->
<link rel="stylesheet" type="text/css" href="/note/resource/css/style.css">
<script src="/note/resource/js/jquery-1.11.3.min.js"></script>
<script src="/note/resource/js/jquery.easings.min.js"></script>
<style type="text/css">
	body {font-size:14px;line-height:1.6;margin:80px auto;max-width:600px;}
	table {border-top: 1px solid #d1d1d1;border-left: 1px solid #d1d1d1;}
	table tr {}
	table td {border-right: 1px solid #d1d1d1;border-bottom: 1px solid #d1d1d1;padding: 10px;text-align: center;}
</style>
</head>
<body>

<table>
	<tbody>
		<tr>
			<td>
				<p><span><strong>표현문자</strong></span></p>
			</td>
			<td>
				<p><span><strong>숫자표현</strong></span></p>
			</td>
			<td>
				<p><span><strong>문자표현</strong></span></p>
			</td>
			<td>
				<p><span><strong>설명</strong></span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>&amp;#00;-&amp;#08;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>사용하지 않음</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>space</span></p>
			</td>
			<td>
				<p><span>&amp;#09;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>수평탭</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>space</span></p>
			</td>
			<td>
				<p><span>&amp;#10;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>줄 삽입</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>&amp;#11;-&amp;#31;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>사용하지 않음</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>space</span></p>
			</td>
			<td>
				<p><span>&amp;#32;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>여백</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>!</span></p>
			</td>
			<td>
				<p><span>&amp;#33;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>느낌표</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>"</span></p>
			</td>
			<td>
				<p><span>&amp;#34;</span></p>
			</td>
			<td>
				<p><span>&amp;quot;</span></p>
			</td>
			<td>
				<p><span>따옴표</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>#</span></p>
			</td>
			<td>
				<p><span>&amp;#35;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>숫자기호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>$</span></p>
			</td>
			<td>
				<p><span>&amp;#36;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>달러</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>%</span></p>
			</td>
			<td>
				<p><span>&amp;#37;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>백분율 기호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>&amp;</span></p>
			</td>
			<td>
				<p><span>&amp;#38;</span></p>
			</td>
			<td>
				<p><span>&amp;amp;</span></p>
			</td>
			<td>
				<p><span>Ampersand</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>'</span></p>
			</td>
			<td>
				<p><span>&amp;#39;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>작은 따옴표</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>(</span></p>
			</td>
			<td>
				<p><span>&amp;#40;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>왼쪽 괄호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>)</span></p>
			</td>
			<td>
				<p><span>&amp;#41;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>오른쪽 괄호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>*</span></p>
			</td>
			<td>
				<p><span>&amp;#42;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>아스트릭</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>+</span></p>
			</td>
			<td>
				<p><span>&amp;#43;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>더하기 기호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>,</span></p>
			</td>
			<td>
				<p><span>&amp;#44;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>쉼표</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>&amp;#45;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>Hyphen</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>.</span></p>
			</td>
			<td>
				<p><span>&amp;#46;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>마침표</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>/</span></p>
			</td>
			<td>
				<p><span>&amp;#47;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>Solidus (slash)</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>0 - 9</span></p>
			</td>
			<td>
				<p><span>&amp;#48;-&amp;#57;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>0부터 9까지</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>:</span></p>
			</td>
			<td>
				<p><span>&amp;#58;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>콜론</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>;</span></p>
			</td>
			<td>
				<p><span>&amp;#59;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>세미콜론</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>&lt;</span></p>
			</td>
			<td>
				<p><span>&amp;#60;</span></p>
			</td>
			<td>
				<p><span>&amp;lt;</span></p>
			</td>
			<td>
				<p><span>보다 작은</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>=</span></p>
			</td>
			<td>
				<p><span>&amp;#61;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>등호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>&gt;</span></p>
			</td>
			<td>
				<p><span>&amp;#62;</span></p>
			</td>
			<td>
				<p><span>&amp;gt;</span></p>
			</td>
			<td>
				<p><span>보다 큰</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>?</span></p>
			</td>
			<td>
				<p><span>&amp;#63;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>물음표</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>@</span></p>
			</td>
			<td>
				<p><span>&amp;#64;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>Commercial at</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>A - Z</span></p>
			</td>
			<td>
				<p><span>&amp;#65;-&amp;#90;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>A부터 Z까지</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>[</span></p>
			</td>
			<td>
				<p><span>&amp;#91;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>왼쪽 대괄호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>\</span></p>
			</td>
			<td>
				<p><span>&amp;#92;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>역슬래쉬</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>]</span></p>
			</td>
			<td>
				<p><span>&amp;#93;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>오른쪽 대괄호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>^</span></p>
			</td>
			<td>
				<p><span>&amp;#94;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>탈자부호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>_</span></p>
			</td>
			<td>
				<p><span>&amp;#95;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>수평선</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>`</span></p>
			</td>
			<td>
				<p><span>&amp;#96;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>Acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>a - z</span></p>
			</td>
			<td>
				<p><span>&amp;#97;-&amp;#122;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>a부터 z까지</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>{</span></p>
			</td>
			<td>
				<p><span>&amp;#123;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>왼쪽 중괄호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>|</span></p>
			</td>
			<td>
				<p><span>&amp;#124;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>수직선</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>}</span></p>
			</td>
			<td>
				<p><span>&amp;#125;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>오른쪽 중괄호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>~</span></p>
			</td>
			<td>
				<p><span>&amp;#126;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>꼬리표</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>&amp;#127;-&amp;#159;</span></p>
			</td>
			<td>
				<p><span>-</span></p>
			</td>
			<td>
				<p><span>사용하지 않음</span></p>
			</td>
		</tr>
		<tr>
			<td><span style="COLOR: #333333"></span></td>
			<td>
				<p><span>&amp;#160;</span></p>
			</td>
			<td>
				<p><span>&amp;nbsp;</span></p>
			</td>
			<td>
				<p><span>Non-breaking space</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>¡</span></p>
			</td>
			<td>
				<p><span>&amp;#161;</span></p>
			</td>
			<td>
				<p><span>&amp;iexcl;</span></p>
			</td>
			<td>
				<p><span>거꾸로된 느낌표</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>￠</span></p>
			</td>
			<td>
				<p><span>&amp;#162;</span></p>
			</td>
			<td>
				<p><span>&amp;cent;</span></p>
			</td>
			<td>
				<p><span>센트 기호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>￡</span></p>
			</td>
			<td>
				<p><span>&amp;#163;</span></p>
			</td>
			<td>
				<p><span>&amp;pound;</span></p>
			</td>
			<td>
				<p><span>파운드</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>¤</span></p>
			</td>
			<td>
				<p><span>&amp;#164;</span></p>
			</td>
			<td>
				<p><span>&amp;curren;</span></p>
			</td>
			<td>
				<p><span>현재 환율</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>￥</span></p>
			</td>
			<td>
				<p><span>&amp;#165;</span></p>
			</td>
			<td>
				<p><span>&amp;yen;</span></p>
			</td>
			<td>
				<p><span>엔</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>|</span></p>
			</td>
			<td>
				<p><span>&amp;#166;</span></p>
			</td>
			<td>
				<p><span>&amp;brvbar;</span></p>
			</td>
			<td>
				<p><span>끊어진 수직선</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>§</span></p>
			</td>
			<td>
				<p><span>&amp;#167;</span></p>
			</td>
			<td>
				<p><span>&amp;sect;</span></p>
			</td>
			<td>
				<p><span>섹션 기호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>¨</span></p>
			</td>
			<td>
				<p><span>&amp;#168;</span></p>
			</td>
			<td>
				<p><span>&amp;uml;</span></p>
			</td>
			<td>
				<p><span>움라우트</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>ⓒ</span></p>
			</td>
			<td>
				<p><span>&amp;#169;</span></p>
			</td>
			<td>
				<p><span>&amp;copy;</span></p>
			</td>
			<td>
				<p><span>저작권</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>ª</span></p>
			</td>
			<td>
				<p><span>&amp;#170;</span></p>
			</td>
			<td>
				<p><span>&amp;ordf;</span></p>
			</td>
			<td>
				<p><span>Feminine ordinal</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>≪</span></p>
			</td>
			<td>
				<p><span>&amp;#171;</span></p>
			</td>
			<td>
				<p><span>&amp;laquo;</span></p>
			</td>
			<td>
				<p><span>왼쪽 꺾인 괄호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>￢</span></p>
			</td>
			<td>
				<p><span>&amp;#172;</span></p>
			</td>
			<td>
				<p><span>&amp;not;</span></p>
			</td>
			<td>
				<p><span>부정</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>&shy;</span></p>
			</td>
			<td>
				<p><span>&amp;#173;</span></p>
			</td>
			<td>
				<p><span>&amp;shy;</span></p>
			</td>
			<td>
				<p><span>Soft hyphen</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>?</span></p>
			</td>
			<td>
				<p><span>&amp;#174;</span></p>
			</td>
			<td>
				<p><span>&amp;reg;</span></p>
			</td>
			<td>
				<p><span>등록상표</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>&amp;hibar;</span></p>
			</td>
			<td>
				<p><span>&amp;#175;</span></p>
			</td>
			<td>
				<p><span>&amp;macr;</span></p>
			</td>
			<td>
				<p><span>Macron accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>°</span></p>
			</td>
			<td>
				<p><span>&amp;#176;</span></p>
			</td>
			<td>
				<p><span>&amp;deg;</span></p>
			</td>
			<td>
				<p><span>Degree sign</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>±</span></p>
			</td>
			<td>
				<p><span>&amp;#177;</span></p>
			</td>
			<td>
				<p><span>&amp;plusmn;</span></p>
			</td>
			<td>
				<p><span>Plus or minus</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>²</span></p>
			</td>
			<td>
				<p><span>&amp;#178;</span></p>
			</td>
			<td>
				<p><span>&amp;sup2;</span></p>
			</td>
			<td>
				<p><span>Superscript two</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>³</span></p>
			</td>
			<td>
				<p><span>&amp;#179;</span></p>
			</td>
			<td>
				<p><span>&amp;sup3;</span></p>
			</td>
			<td>
				<p><span>Superscript three</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>´</span></p>
			</td>
			<td>
				<p><span>&amp;#180;</span></p>
			</td>
			<td>
				<p><span>&amp;acute;</span></p>
			</td>
			<td>
				<p><span>Acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>μ</span></p>
			</td>
			<td>
				<p><span>&amp;#181;</span></p>
			</td>
			<td>
				<p><span>&amp;micro;</span></p>
			</td>
			<td>
				<p><span>Micro sign (Mu)</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>¶</span></p>
			</td>
			<td>
				<p><span>&amp;#182;</span></p>
			</td>
			<td>
				<p><span>&amp;para;</span></p>
			</td>
			<td>
				<p><span>문단기호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>·</span></p>
			</td>
			<td>
				<p><span>&amp;#183;</span></p>
			</td>
			<td>
				<p><span>&amp;middot;</span></p>
			</td>
			<td>
				<p><span>Middle dot</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>¸</span></p>
			</td>
			<td>
				<p><span>&amp;#184;</span></p>
			</td>
			<td>
				<p><span>&amp;cedil;</span></p>
			</td>
			<td>
				<p><span>Cedilla</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>¹</span></p>
			</td>
			<td>
				<p><span>&amp;#185;</span></p>
			</td>
			<td>
				<p><span>&amp;sup1;</span></p>
			</td>
			<td>
				<p><span>Superscript one</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>º</span></p>
			</td>
			<td>
				<p><span>&amp;#186;</span></p>
			</td>
			<td>
				<p><span>&amp;ordm;</span></p>
			</td>
			<td>
				<p><span>Masculine ordinal</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>≫</span></p>
			</td>
			<td>
				<p><span>&amp;#187;</span></p>
			</td>
			<td>
				<p><span>&amp;raquo;</span></p>
			</td>
			<td>
				<p><span>오른쪽 꺾인 괄호</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>¼</span></p>
			</td>
			<td>
				<p><span>&amp;#188;</span></p>
			</td>
			<td>
				<p><span>&amp;frac14;</span></p>
			</td>
			<td>
				<p><span>4분의 1</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>½</span></p>
			</td>
			<td>
				<p><span>&amp;#189;</span></p>
			</td>
			<td>
				<p><span>&amp;frac12;</span></p>
			</td>
			<td>
				<p><span>2분의 1</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>¾</span></p>
			</td>
			<td>
				<p><span>&amp;#190;</span></p>
			</td>
			<td>
				<p><span>&amp;frac34;</span></p>
			</td>
			<td>
				<p><span>4분의 3</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>¿</span></p>
			</td>
			<td>
				<p><span>&amp;#191;</span></p>
			</td>
			<td>
				<p><span>&amp;iquest;</span></p>
			</td>
			<td>
				<p><span>거꾸로된 물음표</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>A</span></p>
			</td>
			<td>
				<p><span>&amp;#192;</span></p>
			</td>
			<td>
				<p><span>&amp;Agrave;</span></p>
			</td>
			<td>
				<p><span>Capital A, grave accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>A</span></p>
			</td>
			<td>
				<p><span>&amp;#193;</span></p>
			</td>
			<td>
				<p><span>&amp;Aacute;</span></p>
			</td>
			<td>
				<p><span>Capital A, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>A</span></p>
			</td>
			<td>
				<p><span>&amp;#194;</span></p>
			</td>
			<td>
				<p><span>&amp;Acirc; </span></p>
			</td>
			<td>
				<p><span>Capital A, circumflex accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>A</span></p>
			</td>
			<td>
				<p><span>&amp;#195;</span></p>
			</td>
			<td>
				<p><span>&amp;Atilde;</span></p>
			</td>
			<td>
				<p><span>Capital A, tilde</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>A</span></p>
			</td>
			<td>
				<p><span>&amp;#196;</span></p>
			</td>
			<td>
				<p><span>&amp;Auml;</span></p>
			</td>
			<td>
				<p><span>Capital A, dieresis or umlaut mark</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>A</span></p>
			</td>
			<td>
				<p><span>&amp;#197;</span></p>
			</td>
			<td>
				<p><span>&amp;Aring;</span></p>
			</td>
			<td>
				<p><span>Capital A, ring (Angstrom)</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>Æ</span></p>
			</td>
			<td>
				<p><span>&amp;#198;</span></p>
			</td>
			<td>
				<p><span>&amp;AElig;</span></p>
			</td>
			<td>
				<p><span>Capital AE diphthong (ligature)</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>C</span></p>
			</td>
			<td>
				<p><span>&amp;#199;</span></p>
			</td>
			<td>
				<p><span>&amp;Ccedil;</span></p>
			</td>
			<td>
				<p><span>Capital C, cedilla</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>E</span></p>
			</td>
			<td>
				<p><span>&amp;#200;</span></p>
			</td>
			<td>
				<p><span>&amp;Egrave;</span></p>
			</td>
			<td>
				<p><span>Capital E, grave accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>E</span></p>
			</td>
			<td>
				<p><span>&amp;#201;</span></p>
			</td>
			<td>
				<p><span>&amp;Eacute;</span></p>
			</td>
			<td>
				<p><span>Capital E, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>E</span></p>
			</td>
			<td>
				<p><span>&amp;#202;</span></p>
			</td>
			<td>
				<p><span>&amp;Ecirc;</span></p>
			</td>
			<td>
				<p><span>Capital E, circumflex accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>E</span></p>
			</td>
			<td>
				<p><span>&amp;#203;</span></p>
			</td>
			<td>
				<p><span>&amp;Euml;</span></p>
			</td>
			<td>
				<p><span>Capital E, dieresis or umlaut mark</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>I</span></p>
			</td>
			<td>
				<p><span>&amp;#204;</span></p>
			</td>
			<td>
				<p><span>&amp;Igrave;</span></p>
			</td>
			<td>
				<p><span>Capital I, grave accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>I</span></p>
			</td>
			<td>
				<p><span>&amp;#205;</span></p>
			</td>
			<td>
				<p><span>&amp;Iacute;</span></p>
			</td>
			<td>
				<p><span>Capital I, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>I</span></p>
			</td>
			<td>
				<p><span>&amp;#206;</span></p>
			</td>
			<td>
				<p><span>&amp;Icirc;</span></p>
			</td>
			<td>
				<p><span>Capital I, circumflex accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>I</span></p>
			</td>
			<td>
				<p><span>&amp;#207;</span></p>
			</td>
			<td>
				<p><span>&amp;Iuml;</span></p>
			</td>
			<td>
				<p><span>Capital I, dieresis or umlaut mark</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>Ð</span></p>
			</td>
			<td>
				<p><span>&amp;#208;</span></p>
			</td>
			<td>
				<p><span>&amp;ETH;</span></p>
			</td>
			<td>
				<p><span>Capital Eth, Icelandic</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>N</span></p>
			</td>
			<td>
				<p><span>&amp;#209;</span></p>
			</td>
			<td>
				<p><span>&amp;Ntilde;</span></p>
			</td>
			<td>
				<p><span>Capital N, tilde</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>O</span></p>
			</td>
			<td>
				<p><span>&amp;#210;</span></p>
			</td>
			<td>
				<p><span>&amp;Ograve;</span></p>
			</td>
			<td>
				<p><span>Capital O, grave accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>O</span></p>
			</td>
			<td>
				<p><span>&amp;#211;</span></p>
			</td>
			<td>
				<p><span>&amp;Oacute;</span></p>
			</td>
			<td>
				<p><span>Capital O, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>O</span></p>
			</td>
			<td>
				<p><span>&amp;#212;</span></p>
			</td>
			<td>
				<p><span>&amp;Ocirc;</span></p>
			</td>
			<td>
				<p><span>Capital O, circumflex accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>O</span></p>
			</td>
			<td>
				<p><span>&amp;#213;</span></p>
			</td>
			<td>
				<p><span>&amp;Otilde;</span></p>
			</td>
			<td>
				<p><span>Capital O, tilde</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>O</span></p>
			</td>
			<td>
				<p><span>&amp;#214;</span></p>
			</td>
			<td>
				<p><span>&amp;Ouml;</span></p>
			</td>
			<td>
				<p><span>Capital O, dieresis or umlaut mark</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>×</span></p>
			</td>
			<td>
				<p><span>&amp;#215;</span></p>
			</td>
			<td>
				<p><span>&amp;times;</span></p>
			</td>
			<td>
				<p><span>Multiply sign</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>Ø</span></p>
			</td>
			<td>
				<p><span>&amp;#216;</span></p>
			</td>
			<td>
				<p><span>&amp;Oslash;</span></p>
			</td>
			<td>
				<p><span>width="130"Capital O, slash</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>U</span></p>
			</td>
			<td>
				<p><span>&amp;#217;</span></p>
			</td>
			<td>
				<p><span>&amp;Ugrave;</span></p>
			</td>
			<td>
				<p><span>Capital U, grave accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>U</span></p>
			</td>
			<td>
				<p><span>&amp;#218;</span></p>
			</td>
			<td>
				<p><span>&amp;Uacute;</span></p>
			</td>
			<td>
				<p><span>Capital U, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>U</span></p>
			</td>
			<td>
				<p><span>&amp;#219;</span></p>
			</td>
			<td>
				<p><span>&amp;Ucirc;</span></p>
			</td>
			<td>
				<p><span>Capital U, circumflex accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>U</span></p>
			</td>
			<td>
				<p><span>&amp;#220;</span></p>
			</td>
			<td>
				<p><span>&amp;Uuml;</span></p>
			</td>
			<td>
				<p><span>Capital U, dieresis or umlaut mark</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>Y</span></p>
			</td>
			<td>
				<p><span>&amp;#221;</span></p>
			</td>
			<td>
				<p><span>&amp;Yacute;</span></p>
			</td>
			<td>
				<p><span>Capital Y, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>Þ</span></p>
			</td>
			<td>
				<p><span>&amp;#222;</span></p>
			</td>
			<td>
				<p><span>&amp;THORN;</span></p>
			</td>
			<td>
				<p><span>Capital Thorn, Icelandic</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>ß</span></p>
			</td>
			<td>
				<p><span>&amp;#223;</span></p>
			</td>
			<td>
				<p><span>&amp;szlig;</span></p>
			</td>
			<td>
				<p><span>Small sharp s, German (sz ligature)</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>a</span></p>
			</td>
			<td>
				<p><span>&amp;#224;</span></p>
			</td>
			<td>
				<p><span>&amp;agrave;</span></p>
			</td>
			<td>
				<p><span>Small a, grave accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>a</span></p>
			</td>
			<td>
				<p><span>&amp;#225;</span></p>
			</td>
			<td>
				<p><span>&amp;aacute;</span></p>
			</td>
			<td>
				<p><span>Small a, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>a</span></p>
			</td>
			<td>
				<p><span>&amp;#226;</span></p>
			</td>
			<td>
				<p><span>&amp;acirc;</span></p>
			</td>
			<td>
				<p><span>Small a, circumflex accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>a</span></p>
			</td>
			<td>
				<p><span>&amp;#227;</span></p>
			</td>
			<td>
				<p><span>&amp;atilde;</span></p>
			</td>
			<td>
				<p><span>Small a, tilde</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>a</span></p>
			</td>
			<td>
				<p><span>&amp;#228;</span></p>
			</td>
			<td>
				<p><span>&amp;auml;</span></p>
			</td>
			<td>
				<p><span>Small a, dieresis or umlaut mark</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>a</span></p>
			</td>
			<td>
				<p><span>&amp;#229;</span></p>
			</td>
			<td>
				<p><span>&amp;aring;</span></p>
			</td>
			<td>
				<p><span>Small a, ring</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>æ</span></p>
			</td>
			<td>
				<p><span>&amp;#230;</span></p>
			</td>
			<td>
				<p><span>&amp;aelig;</span></p>
			</td>
			<td>
				<p><span>Small ae diphthong (ligature)</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>c</span></p>
			</td>
			<td>
				<p><span>&amp;#231;</span></p>
			</td>
			<td>
				<p><span>&amp;ccedil;</span></p>
			</td>
			<td>
				<p><span>Small c, cedilla</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>e</span></p>
			</td>
			<td>
				<p><span>&amp;#232;</span></p>
			</td>
			<td>
				<p><span>&amp;egrave;</span></p>
			</td>
			<td>
				<p><span>Small e, grave accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>e</span></p>
			</td>
			<td>
				<p><span>&amp;#233;</span></p>
			</td>
			<td>
				<p><span>&amp;eacute;</span></p>
			</td>
			<td>
				<p><span>Small e, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>e</span></p>
			</td>
			<td>
				<p><span>&amp;#234;</span></p>
			</td>
			<td>
				<p><span>&amp;ecirc;</span></p>
			</td>
			<td>
				<p><span>Small e, circumflex accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>e</span></p>
			</td>
			<td>
				<p><span>&amp;#235;</span></p>
			</td>
			<td>
				<p><span>&amp;euml;</span></p>
			</td>
			<td>
				<p><span>Small e, dieresis or umlaut mark</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>i</span></p>
			</td>
			<td>
				<p><span>&amp;#236;</span></p>
			</td>
			<td>
				<p><span>&amp;igrave;</span></p>
			</td>
			<td>
				<p><span>Small i, grave accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>i</span></p>
			</td>
			<td>
				<p><span>&amp;#237;</span></p>
			</td>
			<td>
				<p><span>&amp;iacute;</span></p>
			</td>
			<td>
				<p><span>Small i, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>i</span></p>
			</td>
			<td>
				<p><span>&amp;#238;</span></p>
			</td>
			<td>
				<p><span>&amp;icirc;</span></p>
			</td>
			<td>
				<p><span>Small i, circumflex accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>i</span></p>
			</td>
			<td>
				<p><span>&amp;#239;</span></p>
			</td>
			<td>
				<p><span>&amp;iuml;</span></p>
			</td>
			<td>
				<p><span>Small i, dieresis or umlaut mark</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>ð</span></p>
			</td>
			<td>
				<p><span>&amp;#240;</span></p>
			</td>
			<td>
				<p><span>&amp;eth;</span></p>
			</td>
			<td>
				<p><span>Small eth, Icelandic</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>n</span></p>
			</td>
			<td>
				<p><span>&amp;#241;</span></p>
			</td>
			<td>
				<p><span>&amp;ntilde;</span></p>
			</td>
			<td>
				<p><span>Small n, tilde</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>o</span></p>
			</td>
			<td>
				<p><span>&amp;#242;</span></p>
			</td>
			<td>
				<p><span>&amp;ograve;</span></p>
			</td>
			<td>
				<p><span>Small o, grave accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>o</span></p>
			</td>
			<td>
				<p><span>&amp;#243;</span></p>
			</td>
			<td>
				<p><span>&amp;oacute;</span></p>
			</td>
			<td>
				<p><span>Small o, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>o</span></p>
			</td>
			<td>
				<p><span>&amp;#244;</span></p>
			</td>
			<td>
				<p><span>&amp;ocirc;</span></p>
			</td>
			<td>
				<p><span>Small o, circumflex accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>o</span></p>
			</td>
			<td>
				<p><span>&amp;#245;</span></p>
			</td>
			<td>
				<p><span>&amp;otilde;</span></p>
			</td>
			<td>
				<p><span>Small o, tilde</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>o</span></p>
			</td>
			<td>
				<p><span>&amp;#246;</span></p>
			</td>
			<td>
				<p><span>&amp;ouml;</span></p>
			</td>
			<td>
				<p><span>Small o, dieresis or umlaut mark</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>÷</span></p>
			</td>
			<td>
				<p><span>&amp;#247;</span></p>
			</td>
			<td>
				<p><span>&amp;divide;</span></p>
			</td>
			<td>
				<p><span>Division sign</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>ø</span></p>
			</td>
			<td>
				<p><span>&amp;#248;</span></p>
			</td>
			<td>
				<p><span>&amp;oslash;</span></p>
			</td>
			<td>
				<p><span>Small o, slash</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>u</span></p>
			</td>
			<td>
				<p><span>&amp;#249;</span></p>
			</td>
			<td>
				<p><span>&amp;ugrave;</span></p>
			</td>
			<td>
				<p><span>Small u, grave accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>u</span></p>
			</td>
			<td>
				<p><span>&amp;#250;</span></p>
			</td>
			<td>
				<p><span>&amp;uacute;</span></p>
			</td>
			<td>
				<p><span>Small u, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>u</span></p>
			</td>
			<td>
				<p><span>&amp;#251;</span></p>
			</td>
			<td>
				<p><span>&amp;ucirc;</span></p>
			</td>
			<td>
				<p><span>Small u, circumflex accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>u</span></p>
			</td>
			<td>
				<p><span>&amp;#252;</span></p>
			</td>
			<td>
				<p><span>&amp;uuml;</span></p>
			</td>
			<td>
				<p><span>Small u, dieresis or umlaut mark</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>y</span></p>
			</td>
			<td>
				<p><span>&amp;#253;</span></p>
			</td>
			<td>
				<p><span>&amp;yacute;</span></p>
			</td>
			<td>
				<p><span>Small y, acute accent</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>þ</span></p>
			</td>
			<td>
				<p><span>&amp;#254;</span></p>
			</td>
			<td>
				<p><span>&amp;thorn;</span></p>
			</td>
			<td>
				<p><span>Small thorn, Icelandic</span></p>
			</td>
		</tr>
		<tr>
			<td>
				<p><span>y</span></p>
			</td>
			<td>
				<p><span>&amp;#255;</span></p>
			</td>
			<td>
				<p><span>&amp;yuml;</span></p>
			</td>
			<td>
				<p><span>Small y, dieresis or umlaut mark</span></p>
			</td>
		</tr>
	</tbody>
</table>



</body>
</html>
